#!/bin/bash
echo "============================================"
echo "  CropSure AI - Demo Mode"
echo "  IEEE Africa Hackathon 2026"
echo "============================================"
echo ""
echo "Step 1: Starting all services..."
cd $(dirname "$0")/../..
docker compose --env-file .env up --build -d
echo ""
echo "Step 2: Waiting for services to be ready..."
sleep 15
echo ""
echo "Step 3: Loading demo farm data..."
docker compose exec postgres psql -U cropsure -d cropsure_db -f /integration/demo/demo_data.sql
echo "Demo data loaded."
echo ""
echo "Step 4: Opening dashboard..."
xdg-open http://localhost:5173 2>/dev/null || open http://localhost:5173 2>/dev/null || echo "Open http://localhost:5173 in your browser"
echo ""
echo "============================================"
echo "  DEMO CHECKLIST"
echo "============================================"
echo "[ ] 1. Show enrollment screen in Swahili"
echo "[ ] 2. Agent uploads drone photo of farm"
echo "[ ] 3. Trace farm boundary on aerial photo"
echo "[ ] 4. Show premium: KES 900 for 2.5 acres maize"
echo "[ ] 5. Farmer pays via M-Pesa STK push"
echo "[ ] 6. Switch to admin dashboard"
echo "[ ] 7. Show 5 farms on Kenya map"
echo "[ ] 8. Click Kipchoge farm — show stress alert"
echo "[ ] 9. Show NDVI chart dropping 42% below baseline"
echo "[ ] 10. Click Simulate Drought button"
echo "[ ] 11. Watch payout trigger automatically"
echo "[ ] 12. M-Pesa notification fires on demo phone"
echo "[ ] 13. Show WhatsApp message with explanation"
echo "[ ] 14. Show Zawadi farm — completed payout"
echo "============================================"
echo "  Frontend:     http://localhost:5173"
echo "  Backend API:  http://localhost:8000/docs"
echo "  ML Service:   http://localhost:8001/health"
echo "  WhatsApp Bot: http://localhost:5000/health"
echo "  USSD Handler: http://localhost:5001/health"
echo "============================================"
echo "Good luck!"
